---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metric-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: GitRepository
        name: development-helm
  interval: 10s
  targetNamespace: kube-system
  values:
    replicas: 2

